# Generated by Django 4.2 on 2023-05-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizadores',
            options={'verbose_name': 'Utilizadores', 'verbose_name_plural': 'Utilizadores'},
        ),
    ]
